AWSTemplateFormatVersion: "2010-09-09"
Description: "MySQL RDS Security Group"
Parameters:
  stackName:
    Default: "cft-sg-mysql-rds"
    Description: "Name of stack"
    Type: String
  VPCID:
    Default: "vpc-e8069d92"
    Description: "ID of VPC to deploy in"
    Type: String
Resources:
  golfathonSGDev:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL connections
      VpcId: !Ref VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 4.15.102.130/32
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 172.31.16.0/20
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: "MySQLSG"