AWSTemplateFormatVersion: 2010-09-09
Description: "KMS Key for Golfathon Web App"
Parameters:
  stackName:
    Default: "cft-kms-golfathon-dev"
    Description: "Name of stack"
    Type: String
  env:
    Default: "dev"
    Description: "Environment of instance: dev, qa, or prod"
    Type: String
Resources:
  golfathonKMSDev:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS Key for Golfathon Web App"
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy: {
        "Id": "key-consolepolicy-3",
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
            "AWS": "arn:aws:iam::504471836180:root"
            },
            "Action": "kms:*",
            "Resource": "*"
          },
          {
            "Sid": "Allow access for Key Administrators",
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::504471836180:user/kezzhou"
            },
            "Action": [
              "kms:Create*",
              "kms:Describe*",
              "kms:Enable*",
              "kms:List*",
              "kms:Put*",
              "kms:Update*",
              "kms:Revoke*",
              "kms:Disable*",
              "kms:Get*",
              "kms:Delete*",
              "kms:TagResource",
              "kms:UntagResource",
              "kms:ScheduleKeyDeletion",
              "kms:CancelKeyDeletion"
            ],
            "Resource": "*"
          },
          {
            "Sid": "Allow use of the key",
            "Effect": "Allow",
            "Principal": {
            "AWS": [
              "arn:aws:iam::504471836180:role/golfathon-role",
              "arn:aws:iam::504471836180:user/kezzhou"
            ]
          },
            "Action": [
              "kms:Encrypt",
              "kms:Decrypt",
              "kms:ReEncrypt*",
              "kms:GenerateDataKey*",
              "kms:DescribeKey"
            ],
           "Resource": "*"
          },
          {
            "Sid": "Allow attachment of persistent resources",
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::504471836180:role/golfathon-role",
                "arn:aws:iam::504471836180:user/kezzhou"
              ]
            },
            "Action": [
              "kms:CreateGrant",
              "kms:ListGrants",
              "kms:RevokeGrant"
            ],
            "Resource": "*",
            "Condition": {
              "Bool": {
                "kms:GrantIsForAWSResource": "true"
              }
            }
          }
        ]
      }
  golfathonKMSAliasDev:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: alias/golfathonKMSDev
      TargetKeyId:
        Ref: golfathonKMSDev