name 'golfathonWebApp'
maintainer 'Keziah Zhou'
maintainer_email 'kezizhou@gmail.com'
license 'All Rights Reserved'
description 'Cookbook to install PHP and run Golfathon Web App'
long_description 'Cookbook to install PHP and run Golfathon Web App'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/kezizhou/golfathonWebApp'
source_url 'https://github.com/kezizhou/golfathonWebApp'

depends 'docker'
